"""Generations

Revision ID: 763b433aaf4a
Revises:
Create Date: 2018-09-19 12:55:45.996673

"""
import sqlalchemy as sa
import ttgn.pokedex.utils
from alembic import context, op

# revision identifiers, used by Alembic.
revision = '763b433aaf4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    if not ttgn.pokedex.utils.if_x_argument('no-schema', False):
        schema_upgrade()

    if not ttgn.pokedex.utils.if_x_argument('no-data', False):
        data_upgrade()


def downgrade():
    if not ttgn.pokedex.utils.if_x_argument('no-data', False):
        data_downgrade()

    if not ttgn.pokedex.utils.if_x_argument('no-schema', False):
        schema_downgrade()


def schema_upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ttgn_pokedex_models_versions_generation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def schema_downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ttgn_pokedex_models_versions_generation')
    # ### end Alembic commands ###


def data_upgrade():
    try:
        ttgn.pokedex.utils.load_data_migration_if_exists(
            '763b433aaf4a', 'upgrade')
    except Exception:
        data_downgrade()
        schema_downgrade()
        raise


def data_downgrade():
    ttgn.pokedex.utils.load_data_migration_if_exists('763b433aaf4a',
                                                     'downgrade')
